'use strict';

const PHRASE_REPLACEMENTS = [
    ['dieu chinh noi dung', 'điều chỉnh nội dung'],
    ['dieu chinh luong', 'điều chỉnh lương'],
    ['toan quyen', 'toàn quyền'],
    ['quan tri', 'quản trị'],
    ['quan ly', 'quản lý'],
    ['he thong', 'hệ thống'],
    ['nghiep vu', 'nghiệp vụ'],
    ['nhan su', 'nhân sự'],
    ['tuyen dung', 'tuyển dụng'],
    ['phe duyet', 'phê duyệt'],
    ['dieu hanh', 'điều hành'],
    ['cap cong ty', 'cấp công ty'],
    ['cap khoi', 'cấp khối'],
    ['cap phong', 'cấp phòng'],
    ['nguoi su dung', 'người sử dụng'],
    ['hanh chinh', 'hành chính'],
    ['trien khai', 'triển khai'],
    ['phat trien', 'phát triển'],
    ['san pham', 'sản phẩm'],
    ['van hanh', 'vận hành'],
    ['tu van', 'tư vấn'],
    ['giai phap', 'giải pháp'],
    ['thi truong', 'thị trường'],
    ['truyen thong', 'truyền thông'],
    ['phan tich', 'phân tích'],
    ['quy trinh', 'quy trình'],
    ['nghien cuu', 'nghiên cứu'],
    ['kiem thu', 'kiểm thử'],
    ['dam bao', 'đảm bảo'],
    ['bao hanh', 'bảo hành'],
    ['ho tro', 'hỗ trợ'],
    ['ky thuat', 'kỹ thuật'],
    ['giam doc', 'giám đốc'],
    ['phong', 'phòng'],
    ['truong phong', 'trưởng phòng'],
    ['truong nhom', 'trưởng nhóm'],
    ['chuyen vien', 'chuyên viên'],
    ['chuyen gia', 'chuyên gia'],
    ['ky nang', 'kỹ năng'],
    ['ky su', 'kỹ sư'],
    ['vi tri', 'vị trí'],
    ['bo sung', 'bổ sung'],
    ['hop dong', 'hợp đồng'],
    ['thu viec', 'thử việc'],
    ['xac dinh thoi han', 'xác định thời hạn'],
    ['khong xac dinh thoi han', 'không xác định thời hạn'],
    ['ke hoach', 'kế hoạch'],
    ['dinh bien', 'định biên'],
    ['dinh huong', 'định hướng'],
    ['vong', 'vòng'],
    ['sang loc', 'sàng lọc'],
    ['ho so', 'hồ sơ'],
    ['phong van', 'phỏng vấn'],
    ['danh gia', 'đánh giá'],
    ['kinh nghiem', 'kinh nghiệm'],
    ['ung vien', 'ứng viên'],
    ['dai hoc', 'đại học'],
    ['cao dang', 'cao đẳng'],
    ['cong nghe', 'công nghệ'],
    ['thong tin', 'thông tin'],
    ['ket qua', 'kết quả'],
    ['dat yeu cau', 'đạt yêu cầu'],
    ['tiep nhan', 'tiếp nhận'],
    ['trung tuyen', 'trúng tuyển'],
    ['nghi viec', 'nghỉ việc'],
    ['chinh thuc', 'chính thức'],
    ['thuc hien', 'thực hiện'],
    ['dieu chuyen', 'điều chuyển'],
    ['nghi phep', 'nghỉ phép'],
    ['viec gia dinh', 'việc gia đình'],
    ['kham benh', 'khám bệnh'],
    ['ly do', 'lý do'],
    ['ban giao', 'bàn giao'],
    ['nhiem vu', 'nhiệm vụ'],
    ['ky luat', 'kỷ luật'],
    ['quyet dinh', 'quyết định'],
    ['phoi hop', 'phối hợp'],
    ['tien do', 'tiến độ'],
    ['hoan thanh', 'hoàn thành'],
    ['tang cuong', 'tăng cường'],
    ['tai lieu', 'tài liệu'],
    ['dao tao', 'đào tạo'],
    ['xem xet', 'xem xét'],
    ['ghi nhan', 'ghi nhận'],
    ['noi bo', 'nội bộ'],
    ['thay doi', 'thay đổi'],
    ['co hoi', 'cơ hội'],
    ['phan cong', 'phân công'],
    ['thay the', 'thay thế'],
    ['so du', 'số dư'],
    ['tinh den', 'tính đến'],
    ['nhan viec', 'nhận việc'],
    ['hoan tat', 'hoàn tất'],
    ['dong gop', 'đóng góp'],
    ['muc tieu', 'mục tiêu'],
    ['chuyen doi', 'chuyển đổi'],
    ['chuoi', 'chuỗi'],
    ['danh sach', 'danh sách'],
    ['phu hop', 'phù hợp'],
    ['viet nam', 'Việt Nam'],
    ['ha noi', 'Hà Nội'],
    ['ha tang', 'hạ tầng'],
    ['mien bac', 'miền Bắc'],
    ['mien trung', 'miền Trung'],
    ['mien nam', 'miền Nam'],
    ['nguoi than', 'người thân'],
    ['gia dinh', 'gia đình'],
    ['phong ban', 'phòng ban'],
    ['phong hop', 'phòng họp'],
    ['chu tri', 'chủ trì'],
    ['thanh vien', 'thành viên'],
    ['hoi dong', 'hội đồng'],
    ['tinh huong', 'tình huống'],
    ['su co', 'sự cố'],
    ['su dung', 'sử dụng'],
    ['bai test nghiep vu', 'bài test nghiệp vụ'],
    ['bang diem dai hoc', 'bảng điểm đại học'],
    ['cong nghe thong tin', 'công nghệ thông tin'],
    ['he thong thong tin', 'hệ thống thông tin'],
    ['quan tri doanh nghiep', 'quản trị doanh nghiệp'],
    ['quan ly cap cao', 'quản lý cấp cao'],
    ['thuc hien cong viec theo vi tri', 'thực hiện công việc theo vị trí'],
    ['dinh bien tuyen dung dot', 'định biên tuyển dụng đợt'],
    ['tiep nhan theo ke hoach tuyen dung', 'tiếp nhận theo kế hoạch tuyển dụng'],
    ['khong phu hop yeu cau tuyen dung', 'không phù hợp yêu cầu tuyển dụng'],
    ['khong phu hop dot nay', 'không phù hợp đợt này'],
    ['khong duoc duyet do ke hoach du an', 'không được duyệt do kế hoạch dự án'],
    ['chua can thiet trong quy nay', 'chưa cần thiết trong quý này'],
    ['chua du dieu kien', 'chưa đủ điều kiện'],
    ['cho phe duyet', 'chờ phê duyệt'],
    ['da phe duyet', 'đã phê duyệt'],
    ['da duyet ngan sach', 'đã duyệt ngân sách'],
    ['da ket thuc dot tuyen', 'đã kết thúc đợt tuyển'],
    ['da hoan tat ban giao', 'đã hoàn tất bàn giao'],
    ['da ban giao cong viec', 'đã bàn giao công việc'],
    ['da thong bao cho nhan su', 'đã thông báo cho nhân sự'],
    ['dang phong van', 'đang phỏng vấn'],
    ['dang cho phe duyet', 'đang chờ phê duyệt'],
    ['du dieu kien phong van', 'đủ điều kiện phỏng vấn'],
    ['du dieu kien chuyen doi', 'đủ điều kiện chuyển đổi'],
    ['du kien ban giao trong thang', 'dự kiến bàn giao trong tháng'],
    ['bo sung nhan su', 'bổ sung nhân sự'],
    ['bo sung chuyen vien tuyen dung', 'bổ sung chuyên viên tuyển dụng'],
    ['bo sung nhan su theo ke hoach van hanh', 'bổ sung nhân sự theo kế hoạch vận hành'],
    ['bo sung nhan su ha tang', 'bổ sung nhân sự hạ tầng'],
    ['mo rong nhom phat trien san pham', 'mở rộng nhóm phát triển sản phẩm'],
    ['mo rong van hanh cloud', 'mở rộng vận hành cloud'],
    ['thay the nhan su nghi viec', 'thay thế nhân sự nghỉ việc'],
    ['tuyen ky su san pham', 'tuyển kỹ sư sản phẩm'],
    ['tuyen chuyen vien', 'tuyển chuyên viên'],
    ['ke hoach tuyen dung', 'kế hoạch tuyển dụng'],
    ['vong danh gia theo quy trinh tuyen dung', 'vòng đánh giá theo quy trình tuyển dụng'],
    ['phat trien he thong', 'phát triển hệ thống'],
    ['phat trien san pham', 'phát triển sản phẩm'],
    ['nhan su da nghi viec', 'nhân sự đã nghỉ việc'],
    ['hop dong chinh thuc', 'hợp đồng chính thức'],
    ['hop dong thu viec', 'hợp đồng thử việc'],
    ['hop dong xac dinh thoi han', 'hợp đồng xác định thời hạn'],
    ['hop dong khong xac dinh', 'hợp đồng không xác định'],
    ['chuyen hop dong sau thu viec', 'chuyển hợp đồng sau thử việc'],
    ['de xuat cap nhat hop dong dinh ky', 'đề xuất cập nhật hợp đồng định kỳ'],
    ['phu luc hop dong bo sung', 'phụ lục hợp đồng bổ sung'],
    ['ket qua danh gia chua dat', 'kết quả đánh giá chưa đạt'],
    ['ket qua danh gia chua dat yeu cau', 'kết quả đánh giá chưa đạt yêu cầu'],
    ['ket qua phong van bo sung', 'kết quả phỏng vấn bổ sung'],
    ['ket qua so loai bo sung', 'kết quả sơ loại bổ sung'],
    ['danh gia phong van bo sung', 'đánh giá phỏng vấn bổ sung'],
    ['danh gia nghiep vu nhan su', 'đánh giá nghiệp vụ nhân sự'],
    ['danh gia van hanh cloud', 'đánh giá vận hành cloud'],
    ['kiem tra ho so va kinh nghiem', 'kiểm tra hồ sơ và kinh nghiệm'],
    ['chuan bi ho so va bai test', 'chuẩn bị hồ sơ và bài test'],
    ['chuan bi tinh huong xu ly su co', 'chuẩn bị tình huống xử lý sự cố'],
    ['chuan bi ban goc', 'chuẩn bị bản gốc'],
    ['ung vien da duoc tiep nhan', 'ứng viên đã được tiếp nhận'],
    ['ung vien da nhan viec', 'ứng viên đã nhận việc'],
    ['ung vien xac nhan qua email', 'ứng viên xác nhận qua email'],
    ['con ung vien dang xu ly', 'còn ứng viên đang xử lý'],
    ['co ung vien da trung tuyen', 'có ứng viên đã trúng tuyển'],
    ['hoan tat chuoi chuyen doi nhan vien', 'hoàn tất chuỗi chuyển đổi nhân viên'],
    ['quyet dinh tuyen dung bo sung', 'quyết định tuyển dụng bổ sung'],
    ['tuyen dung ky su ha tang', 'tuyển dụng kỹ sư hạ tầng'],
    ['ly do ca nhan', 'lý do cá nhân'],
    ['ly do gia dinh', 'lý do gia đình'],
    ['nghi phep ca nhan', 'nghỉ phép cá nhân'],
    ['nghi phep theo ke hoach', 'nghỉ phép theo kế hoạch'],
    ['ban giao tai lieu du an', 'bàn giao tài liệu dự án'],
    ['lap ke hoach ban giao', 'lập kế hoạch bàn giao'],
    ['danh sach ban giao', 'danh sách bàn giao'],
    ['dieu chuyen noi bo', 'điều chuyển nội bộ'],
    ['dieu chuyen sang doi ha tang', 'điều chuyển sang đội hạ tầng'],
    ['dieu chuyen bo sung', 'điều chuyển bổ sung'],
    ['chuyen doi nghe nghiep', 'chuyển đổi nghề nghiệp'],
    ['can doi nhan su', 'cân đối nhân sự'],
    ['phu hop nang luc cloud', 'phù hợp năng lực cloud'],
    ['cho xem xet', 'chờ xem xét'],
    ['chi tiet dieu chuyen', 'chi tiết điều chuyển'],
    ['nhan su chuyen mot nguoi', 'nhân sự chuyển một người'],
    ['tam dung de xuat', 'tạm dừng đề xuất'],
    ['tam thoi', 'tạm thời'],
    ['nhu cau tam thoi', 'nhu cầu tạm thời'],
    ['vi pham quy trinh truc', 'vi phạm quy trình trực'],
    ['vi pham quy trinh noi bo', 'vi phạm quy trình nội bộ'],
    ['dong gop noi bat', 'đóng góp nổi bật'],
    ['dong gop hieu qua', 'đóng góp hiệu quả'],
    ['hoan thanh vuot muc tieu', 'hoàn thành vượt mục tiêu'],
    ['hoan thanh muc tieu cong viec', 'hoàn thành mục tiêu công việc'],
    ['de xuat ghi nhan dong gop', 'đề xuất ghi nhận đóng góp'],
    ['de xuat thuong sau khi ket thuc thu viec', 'đề xuất thưởng sau khi kết thúc thử việc'],
    ['nhac nho va khau tru theo quy dinh', 'nhắc nhở và khấu trừ theo quy định'],
    ['khau tru theo quy dinh', 'khấu trừ theo quy định'],
    ['thuong dot xuat', 'thưởng đột xuất'],
    ['thuong theo ket qua', 'thưởng theo kết quả'],
    ['ho tro on-call', 'hỗ trợ on-call'],
    ['dung tien do', 'đúng tiến độ'],
    ['hoan thanh co ban', 'hoàn thành cơ bản'],
    ['vuot tien do', 'vượt tiến độ'],
    ['phoi hop co ban', 'phối hợp cơ bản'],
    ['phoi hop tot', 'phối hợp tốt'],
    ['phoi hop chu dong', 'phối hợp chủ động'],
    ['chu dong hoc hoi', 'chủ động học hỏi'],
    ['can cai thien', 'cần cải thiện'],
    ['can ke hoach phat trien', 'cần kế hoạch phát triển'],
    ['can tang cuong tai lieu hoa', 'cần tăng cường tài liệu hóa'],
    ['tiep tuc dao tao', 'tiếp tục đào tạo'],
    ['xem xet ghi nhan', 'xem xét ghi nhận'],
    ['danh gia quy', 'đánh giá quý'],
    ['danh gia truoc khi nghi viec', 'đánh giá trước khi nghỉ việc'],
    ['ghi nhan trong ky', 'ghi nhận trong kỳ'],
    ['so du phep nam tinh den', 'số dư phép năm tính đến'],
    ['dinh huong cong viec', 'định hướng công việc'],
    ['thay doi cong viec', 'thay đổi công việc'],
    ['chua lap ke hoach', 'chưa lập kế hoạch'],
    ['da lap danh sach', 'đã lập danh sách'],
    ['du kien sau thu viec', 'dự kiến sau thử việc'],
    ['cho cap nhat ho so chinh', 'chờ cập nhật hồ sơ chính'],
    ['cho cap phe duyet', 'chờ cấp phê duyệt'],
    ['dai hoc quoc gia ha noi', 'Đại học Quốc gia Hà Nội'],
    ['dai hoc bach khoa ha noi', 'Đại học Bách Khoa Hà Nội'],
    ['dai hoc bach khoa', 'Đại học Bách Khoa'],
    ['dai hoc cong nghe', 'Đại học Công nghệ'],
    ['cao dang fpt', 'Cao đẳng FPT'],
    ['thieu kinh nghiem', 'thiếu kinh nghiệm'],
    ['chua co kinh nghiem', 'chưa có kinh nghiệm'],
    ['tot nghiep dai hoc', 'tốt nghiệp đại học'],
    ['dap ung yeu cau vi tri', 'đáp ứng yêu cầu vị trí'],
    ['dap ung tieu chi phong van', 'đáp ứng tiêu chí phỏng vấn'],
    ['ho so ung vien da kiem tra', 'hồ sơ ứng viên đã kiểm tra'],
    ['kinh nghiem phat trien ERP', 'kinh nghiệm phát triển ERP'],
    ['kinh nghiem lam viec voi Azure', 'kinh nghiệm làm việc với Azure'],
    ['da van hanh he thong thuc te', 'đã vận hành hệ thống thực tế'],
    ['phan tich log khoanh vung va rollback', 'phân tích log, khoanh vùng và rollback'],
    ['tra loi chua day du', 'trả lời chưa đầy đủ'],
    ['giam sat he thong nhu the nao', 'giám sát hệ thống như thế nào'],
    ['su dung log va canh bao', 'sử dụng log và cảnh báo'],
    ['nam vung cloud', 'nắm vững cloud'],
    ['thong bao', 'thông báo'],
    ['dong y nhu cau', 'đồng ý nhu cầu'],
    ['duyet ngan sach', 'duyệt ngân sách'],
    ['tiep tuc bo nhiem', 'tiếp tục bổ nhiệm'],
    ['nhan vien', 'nhân viên'],
    ['chu dong hoc Azure', 'chủ động học Azure'],
    ['trinh bay ro rang', 'trình bày rõ ràng'],
    ['thieu kien thuc', 'thiếu kiến thức'],
    ['giao tiep', 'giao tiếp'],
    ['kiem tra backup', 'kiểm tra backup'],
    ['mang ban goc', 'mang bản gốc'],
    ['huy theo yeu cau kinh doanh', 'hủy theo yêu cầu kinh doanh'],
    ['yeu cau du lieu mau', 'yêu cầu dữ liệu mẫu'],
    ['khong chap thuan', 'không chấp thuận'],
    ['chua co nhu cau', 'chưa có nhu cầu'],
    ['nhu cau ca nhan', 'nhu cầu cá nhân'],
    ['do chinh xac', 'độ chính xác'],
    ['dung han', 'đúng hạn'],
    ['lam viec nhom', 'làm việc nhóm'],
    ['hoc hoi va cai tien', 'học hỏi và cải tiến'],
    ['cham tien do', 'chậm tiến độ'],
    ['it loi', 'ít lỗi'],
    ['vuot ky vong', 'vượt kỳ vọng'],
    ['tien bo ro net', 'tiến bộ rõ nét'],
    ['chat luong', 'chất lượng'],
    ['cong viec', 'công việc'],
    ['thoi gian', 'thời gian'],
    ['dung quy dinh', 'đúng quy định'],
    ['khong dat', 'không đạt'],
    ['chua dat', 'chưa đạt'],
    ['co tien bo', 'có tiến bộ'],
    ['kha', 'khá'],
    ['tot', 'tốt'],
    ['dat', 'đạt'],
    ['vuot', 'vượt'],
    ['thap', 'thấp'],
    ['it', 'ít'],
    ['loi', 'lỗi'],
    ['va', 'và'],
    ['chat', 'chất'],
    ['luong', 'lượng'],
    ['cong', 'công'],
    ['viec', 'việc'],
    ['moi', 'mới'],
    ['thang', 'tháng'],
    ['ngay', 'ngày'],
    ['quy nay', 'quý này'],
    ['theo quy', 'theo quý'],
    ['2 nam', '2 năm'],
    ['3 nam', '3 năm'],
    ['0 nam', '0 năm']
];

const PARTIAL_REPLACEMENTS = [
    ['phối hop', 'phối hợp'],
    ['phát trịển', 'phát triển'],
    ['Chat luong', 'Chất lượng'],
    ['Phối hop', 'Phối hợp']
];

const NON_CONTENT_COLUMNS = new Set([
    'status', 'skill_level', 'criteria_type', 'leave_type', 'offer_status', 'overall_result',
    'screening_result', 'result', 'record_type', 'decision_type', 'source_type', 'round_type',
    'format_type', 'action', 'document_type', 'entity_type', 'payment_method', 'employment_status',
    'username', 'email', 'phone',
    'full_name', 'short_name', 'employee_name', 'signer_name', 'approver_name', 'proposer_name',
    'creator_name', 'decision_by_name', 'manager_name', 'related_person_name', 'bank_account_holder'
]);

const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const replacementPattern = (value) => new RegExp(`(^|[^\\p{L}])(${escapeRegExp(value)})(?=$|[^\\p{L}])`, 'giu');

function preserveCase(match, replacement) {
    if (match === match.toUpperCase()) return replacement.toUpperCase();
    if (match[0] === match[0].toUpperCase()) return replacement[0].toUpperCase() + replacement.slice(1);
    return replacement;
}

function applyReplacement(value, from, to) {
    return value.replace(replacementPattern(from), (_, prefix, match) => `${prefix}${preserveCase(match, to)}`);
}

function normalizeVietnameseText(value) {
    if (typeof value !== 'string' || !/[A-Za-z]/.test(value)) return value;

    let normalized = value;
    for (const [from, to] of [...PHRASE_REPLACEMENTS].sort((left, right) => right[0].length - left[0].length)) {
        normalized = applyReplacement(normalized, from, to);
    }
    if (/[^\x00-\x7F]/.test(normalized)) {
        for (const [from, to] of PARTIAL_REPLACEMENTS) normalized = normalized.replace(new RegExp(escapeRegExp(from), 'g'), to);
        return normalized;
    }
    normalized = normalized.replace(/(\b\d+\s+)nam\b/gi, (_, prefix) => `${prefix}năm`);
    return normalized;
}

function shouldNormalizeColumn(column) {
    return !NON_CONTENT_COLUMNS.has(column);
}

module.exports = { normalizeVietnameseText, shouldNormalizeColumn };
