"use client";

import Link from "next/link";
import { ArrowUpRight, CalendarClock, Check, ChevronRight, CircleAlert, Clock3, FileCheck2, Plus, TrendingUp, UsersRound } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { formatNumber } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const tones = { teal: "bg-teal-50 text-teal-700", amber: "bg-amber-50 text-amber-700", violet: "bg-violet-50 text-violet-700", rose: "bg-rose-50 text-rose-700" };

export function DashboardOverview() {
  const { data, isLoading } = useQuery({ queryKey: ["dashboard"], queryFn: api.dashboard });
  if (isLoading || !data) return <div className="grid min-h-[500px] place-items-center text-sm text-slate-400">Đang tải trung tâm điều hành...</div>;
  return <div className="space-y-8">
    <section className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-teal-700"><span className="size-2 rounded-full bg-teal-500" /> Friday, 04 September 2026</div><h1 className="font-display text-3xl font-bold tracking-tight text-slate-950 lg:text-4xl">Buổi sáng tốt lành, <span className="text-teal-700">Nhung.</span></h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Đây là nhịp vận hành nhân sự của BRAVO hôm nay. Có <b className="text-slate-800">9 chứng từ</b> đang cần được xem xét.</p></div><div className="flex gap-2"><Button variant="secondary"><CalendarClock size={16} /> Lịch hôm nay</Button><Button><Plus size={16} /> Tạo chứng từ</Button></div></section>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{data.kpis.map((kpi) => <Card key={kpi.label} className="relative overflow-hidden"><div className="absolute right-0 top-0 size-24 rounded-bl-full bg-slate-50" /><CardContent className="relative p-5"><div className="mb-5 flex items-start justify-between"><div className={`grid size-10 place-items-center rounded-xl ${tones[kpi.tone]}`}><TrendingUp size={18} /></div><span className="text-xs font-bold text-teal-700">{kpi.trend}</span></div><div className="font-display text-3xl font-bold tracking-tight text-slate-950">{typeof kpi.value === "number" ? formatNumber(kpi.value) : kpi.value}</div><div className="mt-1 text-sm font-semibold text-slate-600">{kpi.label}</div><div className="mt-3 text-xs text-slate-400">{kpi.detail}</div></CardContent></Card>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.25fr_0.75fr]"><Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Nhịp tuyển dụng</CardTitle><p className="mt-1 text-xs text-slate-400">Ứng viên theo từng điểm chạm trong pipeline</p></div><Link href="/recruitment" className="flex items-center gap-1 text-xs font-bold text-teal-700">Mở pipeline <ArrowUpRight size={14} /></Link></CardHeader><CardContent><div className="space-y-4 pt-2">{data.pipeline.map((stage, index) => <div key={stage.label}><div className="mb-1.5 flex justify-between text-xs"><span className="font-semibold text-slate-600">{stage.label}</span><span className="font-bold text-slate-900">{stage.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-teal-700 to-teal-400" style={{ width: `${Math.max(8, stage.count / 28 * 100)}%`, opacity: 1 - index * .1 }} /></div></div>)}</div><div className="mt-6 flex items-center justify-between rounded-xl bg-teal-50 p-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-white text-teal-700"><UsersRound size={17} /></div><div><div className="text-xs font-bold text-teal-900">Tỷ lệ chuyển đổi</div><div className="text-[11px] text-teal-700/70">Mới tiếp nhận → đi làm</div></div></div><div className="font-display text-2xl font-bold text-teal-800">7.1%</div></div></CardContent></Card><Card><CardHeader><CardTitle>Cơ cấu nhân sự</CardTitle><p className="mt-1 text-xs text-slate-400">Thực tế so với định biên theo đơn vị</p></CardHeader><CardContent><div className="space-y-5">{data.departments.map((department) => <div key={department.name}><div className="mb-1.5 flex justify-between gap-3 text-xs"><span className="truncate font-semibold text-slate-600">{department.name}</span><span className="shrink-0 font-bold text-slate-900">{department.count}/{department.target}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-800" style={{ width: `${department.count / department.target * 100}%` }} /></div></div>)}</div></CardContent></Card></div>
    <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Hàng đợi phê duyệt</CardTitle><p className="mt-1 text-xs text-slate-400">Các chứng từ gần nhất theo workflow của bạn</p></div><Button variant="ghost" size="sm">Xem tất cả <ChevronRight size={14} /></Button></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-y border-slate-100 bg-slate-50/70 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3 font-bold">Chứng từ</th><th className="px-5 py-3 font-bold">Nội dung</th><th className="px-5 py-3 font-bold">Đơn vị</th><th className="px-5 py-3 font-bold">Mức độ</th><th className="px-5 py-3 text-right font-bold">Xử lý</th></tr></thead><tbody className="divide-y divide-slate-100">{data.approvals.map((item) => <tr key={item.code} className="hover:bg-teal-50/30"><td className="px-5 py-4"><div className="font-mono text-xs font-bold text-teal-700">{item.code}</div><Badge tone={item.type === "Nghỉ phép" ? "blue" : item.type === "Khen thưởng" ? "violet" : "teal"}>{item.type}</Badge></td><td className="px-5 py-4"><div className="font-semibold text-slate-800">{item.title}</div><div className="mt-1 flex items-center gap-1 text-xs text-slate-400"><Clock3 size={12} /> {item.age}</div></td><td className="px-5 py-4 text-xs text-slate-500">{item.owner}</td><td className="px-5 py-4"><Badge tone={item.priority === "Khẩn" ? "rose" : item.priority === "Cao" ? "amber" : "slate"}>{item.priority}</Badge></td><td className="px-5 py-4 text-right"><Button variant="secondary" size="sm">Mở phiếu</Button></td></tr>)}</tbody></table></div></CardContent></Card>
    <div className="grid gap-5 md:grid-cols-3"><Card className="border-teal-200 bg-teal-700 text-white"><CardContent className="p-5"><FileCheck2 className="mb-5 text-teal-200" size={24} /><h3 className="font-display text-lg font-bold">Chuẩn hóa dữ liệu</h3><p className="mt-2 text-xs leading-5 text-teal-100">Tỷ lệ hồ sơ có đủ thông tin định danh đang đạt 94%.</p><div className="mt-5 h-1.5 rounded-full bg-white/20"><div className="h-full w-[94%] rounded-full bg-white" /></div></CardContent></Card><Card><CardContent className="p-5"><CircleAlert className="mb-5 text-amber-600" size={24} /><h3 className="font-display text-lg font-bold">5 hợp đồng sắp hết hạn</h3><p className="mt-2 text-xs leading-5 text-slate-500">Cần theo dõi trong 30 ngày tới để tránh gián đoạn.</p><Link href="/people" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-teal-700">Xem danh sách <ArrowUpRight size={14} /></Link></CardContent></Card><Card><CardContent className="p-5"><Check className="mb-5 text-violet-600" size={24} /><h3 className="font-display text-lg font-bold">98% báo cáo đúng hạn</h3><p className="mt-2 text-xs leading-5 text-slate-500">46 báo cáo đã được tạo trong kỳ hiện tại.</p><Link href="/reports" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-teal-700">Mở trung tâm báo cáo <ArrowUpRight size={14} /></Link></CardContent></Card></div>
  </div>;
}
